# 异常

## 1.关于异常：
​    1.正常执行逻辑时，发生预料之外的错误称之为异常；

​    2.在编写程序时，不仅要处理'正确'的逻辑，也要预估并处理可能发生的异常来保证程序的健壮性；

## 2.Java中的异常机制:

	### 1.异常类:

​		java中通过类来描述发生的异常，并分别为不同的异常提供了不同的异常类；在发生异常时，通过创建异常类的实例对象来存储异常信息；

​		java中已经提前预置了一部分表示异常的类，其继承结构以及常见异常类型如下：

```java
// 所有的异常类最终都继承自Object类
Object
    |--Throwable:// 所有异常类的父类
    	|--Error：// 表示JVM在运行中发生的异常
    		|--OutOfMemoryError; // 比如：内存溢出异常
        |--Exception：// 表示应用在运行中发生的异常，分为Runtime Exception和Checked Exception
            // 运行时异常,凡继承自RunctimeException的异常都称之为Runtime Exception
            |--RuntimeException： 
                |--NullPointerException //比如：空指针异常
                |--ArrayIndexOutOfBoundsException //比如：数组越界异常
                |--NumberFormatException  //比如：数字格式化异常
                |--...其他运行时异常
            // 凡继承自Exception的异常都称之为Checked Exception
            |--IOException	//比如：文件IO异常
            |--EOFException 
            |--FileException
            |--SQLException
            |--ClassNotFoundException
            |--...其他编译时时异常
```

### 2.关于Error和Exception:

​		`Error`表示`JVM`发生的异常，发生此类异常时表明`JVM`运行遇到问题，比如内存耗尽导致 `OutOfMemoryError` 异常，一旦发生`Error`异常时`JVM`无法再继续运行下去，只能选择结束程序；应用本身无法干预和解决此类异常，只能听任`JVM`处理！

​		`Exception`表示应用程序发生的异常，由业务运行导致；可以选择由业务通过`try...catch`来捕获并处理，也可以选择交给`JVM`来处理，如果交给`JVM`的话，通常会将异常信息打印至控制台并结束当前应用程序！而`Exception`类型的异常又可以进一步分为`Runtime Exception`和`Checked Exception`；其中`Runtime Exception`类型的异常并不要求必须处理，可以选择捕获并处理，也可以选择继续抛出，也可以选择放任不管；但是`Checked Exception`类型的异常无论是捕获并处里还是继续抛出，总之要求必须处理；

```java
public class ExceptionTest{
    public static void main(String[] args) throws Mye {
        //对于RuntimeException类型的异常可以选择不处理，编译期间也不会报错
        throw new ClassCastException();
        //对于Checked Exception类型的异常要求必须处理，否则编译也不能通过；
		throw new ClassNotFoundException();
    }
```

### 3.自定义异常类:

​		除过系统预置的异常类以外，还可以根据需要自定义异常类，自定义的异常类继承自`Exception`或者`RuntimeException`;在自定义异常类时必须提供一个无参构造方法和一个接受`String`类型参数的构造方法;

​		如果自定义的异常类直接或者间接继承自`Exception`,那么自定义的异常是`Checked Exception`类型;如果自定义的异常类直接或者间接继承自`RuntimeException`,那么自定义的异常也是`Runtime Exception`类型;

```java
//如果继承自Exception，那么自定义异常是Checked Exception类型的异常
public class MyException extends Exception
{
    public MyException()
    {
        /*无参构造方法*/
    }
    public MyException(String exceptionMessage)
    {
        /*有参构造方法*/
    }
}

//如果继承自RuntimeException，那么自定义异常是Runtime Exception类型的异常
public class MyRunException extends RuntimeException
{
    public MyException()
    {
        /*无参构造方法*/
    }
    public MyException(String exceptionMessage)
    {
        /*有参构造方法*/
    }
}
```

## 3.声明和抛出异常:

	### 1.声明异常：

​        如果当前方法对于可能发生的异常不知道如何处理，却要求调用方必须处理此种异常时，可以通过`throws`来声明当前方法可能发生的异常；

​		通过throws关键字可以声明多个需要调用方处理的异常，多个异常之间使用`,`隔开；如:

```java
 public void testException()
     throws Exception1,Exception2{
     
 }
```

​		调用方在调用有通过`throws`声明异常的方法时，必须处理被调用方通过`throws`声明的异常；如果调用方知道如何处理，可以使用try...catch处理，如果不知道可以继续使用throws关键字抛出；

```java
public void testException()
			throws Exception1,Exception2{
	//方法体
}

//调用testException方法时必须对异常进行处理
//通过try...catch进行处理
public void test(){
    try{
        testException();
    }catch(Exception1|Exception2 e){
        e.getMEssage();
    }
}
//如果当前方法不知如何处理，也可以继续使用throws声明异常，然后又下一级调用方处理
public void test() throws Exception1,Exception2 {
        testException();
}
        3.通过throws声明的方法在被调用时，编译阶段就会检查是否处理了声明的异常，因此调用方可以选择显式的使用try...catch..来捕获并处理，或者继续使用throws声明由上一个调用方处理；如：
            //当前方法不能处理，由当前方法的调用方处理，继续使用throws声明异常
            public void testExc() 
                    throws Exception1,Exception2{
                    testException()
            }
```

		### 2.抛出异常：

​    1.在程序运行过程中，如果发生了java预置的异常，那么程序会自动抛出；在实际业务中也可以根据业务逻辑的需要使用`throw`关键字手动抛出异常；
​    2.`throw`关键字抛出异常语法：

```java
throw new Exception("异常信息")
```

## 4.捕获并处理异常:

​		默认情况下，如果没有对发生的异常进行处理时，`JVM`会将异常的详细信息打印至控制台，并终止程序的运行；应用本身也可以选择通过`try ... catch`来捕获并处理发生的异常；

		### 1.try ... catch语法结构:

```java
try{
	/*有可能发生异常的正常业务代码*/
}catch (AException e1){
	/* 捕获并处理预置异常*/
}catch (BException e2){
	/* 捕获并处理预置异常*/
}finally{
	/* 无论是否发生异常都会执行该代码*/
}
```

### 2.try语句块:

​		在try语句块中放置正常执行但有可能发生异常的代码；其语法结构如下:

```java
try{
	/*有可能发生异常的正常业务代码*/
}
```

### 3.catch语句块:

​		`catch`语句块用来捕获发生的异常；其语法结构如下：

```java
catch (ExceptionType e){
	/* 捕获并处理预置异常*/
}
```

​		其中`ExceptionType`表示需要捕获的异常，e表示当前异常类的实例对象；通过该异常的实例对象即可获取异常的详细信息:

```java
//获取发生的异常信息，以字符串形式返回；
e.getMessage();
//获取发生的异常栈信息，以字符串形式返回；
e.getStackTrace();
//向控制台打印异常栈信息；
e.printStackTrace();
//向指定输出流中打印异常栈信息；
e.printStackTrace(PrintStream s);
```

​		Java也支持同时使用多个`catch语句块`来捕获多个不同的异常，结构如下：

```java
catch (ExceptionType1 e){
	/* 捕获并处理预置异常*/
}
catch (ExceptionType2 e){
	/* 捕获并处理预置异常*/
}
```

​		使用多个catch捕获多个异常时，多个异常的范围从上至下应该逐级增大，不可以将范围较大的异常放在上面，否则下面范围较小的异常永远无法被捕获到；

​		JDK1.7对于捕获多个异常新增了更简洁的语法,其语法结构如下：

```java
 /*
  * 需要捕获的多个异常使用 | 分隔开；
  * e仍然表示捕获到的异常的实例对象，e有隐式的final修饰，是一个不可变量，不允许在catch语句快中对e重新赋值！
  */
catch (AException|BException|CException e){}
```

### 4.finally语句块:

​		`finally`语句块中的代码无论`try`块中是否发生异常，都会执行；一般用来在`finally`中进行资源回收的操作;但是对于finally有以下几个事项需要注意:

​	**1.一下几种情况不会执行`finlly`语句块中的代码:**

​		1.如果`try`或者`catch`语句块中有执行system.exit()代码时，执行该行代码只和JVM将会立即结束，此时不会再继续执行`finlly`中的代码；

​		2.执行`finally`语句块的前提是要执行到`try`块，如果代码在执行`try`块之前已经结束，那么`finally`中的代码同样不会执行；

​		3.如果`try`或者`catch`语句块中有执行 Runtime.getRuntime().halt(1)代码时，执行该行代码只和JVM将会立即结束，此时不会再继续执行`finlly`中的代码；

​		4.如果守护线程在执行`try`或者`catch`中的代码时所有非守护线程运行完成，那么JVM将会立即结束，守护线程将不会再有机会执行`finally`中的代码；

​	**2.在一下几种情况下，会优先执行`finally`中的代码:**

​		1.`try`或者`catch`语句块中执行了`return`语句时，会先计算`return`之后的表达式的值，然后查看当前异常处理流程是否有`finally`，如果有的话会先执行`finally`中的代码，然后再返回try或者`catch`中执行`return`语句，将表达式的值返回；

​		2.如果`finally`语句块中同样有`return`语句时，将不再执行try或者`catch`中的`return`语句，但是`try`或者`catch`中`return`语句之后的表达式会先于`finally`中的代码执行，只是不会讲表达式的值返回而已！

​	**3.关于资源回收:**

​		通常情况下会利用finally中代码块在无论是否发生异常都会执行的特性进行资源的回收处理操作；但是需要手动显式添加具体处理代码；在JDK1.7之后，几乎所有的资源类均实现了`AutoCloseable`或者`Closeable`接口中的`close`方法，因此在JDK1.7以上，资源的回收都会在`try`块中自动进行，无需再添加`finally`语句块！

	### 5.使用try...catch处理异常的建议:

​	 1.异常处理的类型要精确：避免直接捕获Exception或者RuntimeException异常甚至直接捕获Throwable类型的异常；

​     2.异常处理的范围要合适：只处理有可能发生异常的代码，避免try块过大，过滤掉本应该被解决的语法错误或者业务错误；

​     3.异常处理的使用要适度：不要使用异常处理的方式代替错误处理，尽量手动提前处理有可能发生的错误，避免滥用异常处理机制；

​     4：异常处理情况要全面：对一切可能发生的异常情况进行处理；避免漏掉本该处理的异常情况，尤其在使用第三方类库、模块时，要及时了解需要处理的异常；

​     5：不要隐藏捕获到的异常，更不能对捕获到的异常置之不理：要根据异常级别和类型来记录异常，然后以更合适的方式报告异常；

​     6：不能让异常的处理掩盖掉业务逻辑：当前发生异常的方法必须要能够让调用方得知此刻发生了异常，而不是掩盖异常之后汇报null值，否则调用方将无从得知此刻是本就没有数据还是发生了异常没有获取到数据；

## 5.关于Runtime Exception 和 Checked Exception:

### 1.两种异常的设计意义:

​		Java在设计异常体系时设计了两种异常，分别是`Runtime Exception`和`Checked Exception`；`Runtime Exception`类型的异常不是必须要处理的，既可以选择使用`try ... catch`捕获并处理，也可以选择使用`throws`声明当前要抛出的异常，还可以选择完全不处理，异常会继续上抛直至被捕获并处理！但是`Checked Exception`类型的异常必须显式的处理，要么使用`try ... catch`来处理，要么通过`throws`将异常进行声明，由下一级调用者处理；

​		`Checked Exception`的设计思想在于：有些情况下我们无论如何也无法规避某些异常，无论我们多么完善流程可能还是有发生异常的可能，那么这些异常就要求必须处理掉来保证程序的健壮；比如对于文件内容的访问，即便在读取文件内容之前先检测文件是否存在、文件是否有内容等等，但是在真正读取文件内容时，还是有可能因为磁盘或者其他原因导致读取失败，既然无法保证一定读取成功那就要有制定B计划来应对这种可能发生的异常；也就是必须捕获处理或者继续抛出生异常！

​		`Runtime Exception`的设计思想在于：某些情况下，报告异常是因为代码、逻辑等原因导致出错了，系统报告异常并不是为了让我们去捕获然后处理掉异常来保证程序健壮性的，而是希望通过异常来告诉我们代码哪里出错了？为何出错的？希望能够通过异常信息来解决掉这种错误，并不是非得要通过try...catch来处理掉才行！

### 2.Checked Exception的问题:

​		对于`Checked Exception`和`Runtime Exception`各有存在的道理；`Checked Exception`的优势就在于能够强制程序处理指定的异常，避免程序忘记或者没有处理相关异常导致程序健壮性受到影响；但是`Checked Exception`在实际应用中也会带来一些问题：

​		1.异常处理路线过长：调用链比较长的情况下，`Checked Exception`会导致每一级都要知晓需要处理的异常，比如以下调用链：	`A->B->C->D`；如果`D`中有抛出`Checked Exception`类型的异常，但是在C、B都不知道如何处理时只能`throws`,然后给A来进行处理，然而我们的目标仅仅只是在A中处理D中的异常而已，此时此刻却不得不在整个调用链上`throws`异常！

​		 2.导致代码变动风险增加：对于`Checked Exception`类型的异常，调用方必须显示处理，否则代码无法运行！还是对于以下调用链：`A->B->C->D`；如果D中抛出`Checked Exception`异常，在A中对该异常处理时还需要再C和B中逐级`throws`，如果D中修改或者增加了要抛出的`Checked Exception`异常，那么不仅仅要改A中的处理逻辑，B和C中也要修改或者增加`throws`的异常！

### 3.Runtime Exception的问题:

​		对于`Runtime Exception`异常，系统并不强制处理，发生异常时会安装 调用链自动上抛，直至遇到能够处理该异常的代码来处理即可；可以减轻异常链路，避免异常和代码强行耦合！但是`Runtime Exception`因为不是强制的，就又可能遗漏掉某些应当处理的异常！
